### ISSUE TITLE
번역문제 

### ISSUE THREAD

**Issue by ghost** [cjhyuky/MA-XML-MIUI12-KOREAN#3]
번역이 이상하게 되어있어서 픽스 요청드립니다.
내용 
miui 12 eu롬 12.3.0 버전
해당앱 연락처 < com android contacts >

![Screenshot_2020-10-30-15-58-00-213_com android contacts](https://user-images.githubusercontent.com/68238321/97778465-b5080200-1bba-11eb-9eb1-54cf72c7e0b1.jpg)

**Comment by miner7222** [comment]
https://github.com/cjhyuky/MA-XML-MIUI12-KOREAN/commit/d84c0e46a44b7c9fd1c9a2804b415e0698efa0c7

제보 감사합니다.
