### ISSUE TITLE
EU rom 21.8.11 trouble in Korea

### ISSUE THREAD

**Issue by wrc2008** [cjhyuky/MA-XML-MIUI12-KOREAN#4]
Hi, thanks for your effort in advance.

I'm a big fan of EU from, and I faced trouble with miui 12.6 (EU rom 21.8.11)
Phone model: Mi 10T Pro
Mobile carrier: SKT 

1. Phone number recognition (auto recognition) failed.
   -  All Korean credit card apps using phone number auto-recognition.
   - But auto recognition failed since I update miui 12.6.
2. Camera failed.
   - Camera suddenly turned off when I am using the in-app camera function.
   - 10.8M camera didn't operate.
   - Camera focus (image had blur)

Many thanks for considering my request.

**Comment by ingbrzy** [comment]
not a translation issues..
1 - Enable permissions for read contacts
2 - Camera driver issue

**Comment by wrc2008** [comment]
> not a translation issues..
> 1 - Enable permissions for read contacts
   - It's not related to contacts. The apps failed to identify my number.
> 2 - Camera driver issue
   - I just found some comments from the EU rom site thanks.

**Comment by itscutefox** [comment]
Hello, I’m Korean translator of xiaomi.eu project. 

As we introduced our project on README.md, it is translation project not technology related. 
ONLY TRANSLATION-RELATED ISSUE can be solved here.


1. Make sure you have allowed the permission.

Home Screen(홈 화면) > Long Press ‘the app’ > App info(앱 정보) > Permissions(권한) > Get device info(기기 정보 불러오기) > Always allow(항상 허용)


2. Visit xiaomi.eu and find solution or report issue descriptive.


Best regards,

**Comment by wrc2008** [comment]
> Hello, I’m Korean translator of xiaomi.eu project.
> 
> As we introduced our project on README.md, it is translation project not technology related.
> ONLY TRANSLATION-RELATED ISSUE can be solved here.
> 
> 1. Make sure you have allowed the permission.
> 
> Home Screen(홈 화면) > Long Press ‘the app’ > App info(앱 정보) > Permissions(권한) > Get device info(기기 정보 불러오기) > Always allow(항상 허용)
> 
> 1. Visit xiaomi.eu and find solution or report issue descriptive.
> 
> Best regards,

Thank you. I fixed item 1 but still searching for the solution for the camera...
